# Generated by Django 4.1.7 on 2023-03-14 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('knihovna', '0004_kniha_vydavatelstvi_alter_kniha_pocet_stran_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Zadej text recenze', verbose_name='Text recenze')),
                ('kniha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='knihovna.kniha', verbose_name='Kniha')),
                ('recenzent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Recenzent')),
            ],
        ),
    ]
