# Generated by Django 4.1.7 on 2023-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0005_recenze'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenze',
            name='hodnoceni',
            field=models.PositiveSmallIntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], default=3, verbose_name='Hodnocení'),
        ),
    ]
