# Generated by Django 4.1.7 on 2023-03-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knihovna', '0006_recenze_hodnoceni'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recenze',
            options={'ordering': ['kniha', 'recenzent'], 'verbose_name': 'Recenze', 'verbose_name_plural': 'Recenze'},
        ),
        migrations.AddField(
            model_name='recenze',
            name='cas',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
